services:
  postgres:
    image: postgres:latest
    container_name: postgres_url
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cabeca
      POSTGRES_DB: urlshortener
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: